name: check xcode build time

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      name: "Select Xcode"
      with:
        xcode-version: ~16.2
     #   action: none # This finds and selects Xcode

    - name: Select Xcode
      uses: mxcl/xcodebuild@v3
      with:
          xcode: ~16.2
          action: none # This finds and selects the specified Xcode version
