name: check xcode build time

on: push

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      name: "Select Xcode"
      with:
        xcode-version: ~16.2
     #   action: none # This finds and selects Xcode
