name: Enable Corepack and Use Yarn

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14', 'macos-15', 'macos-15-large']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies using Yarn
      run: yarn install
