name: Test for python module

on: [workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-15-large, macos-15, macos-14, macos-14-large]
        py: [3.12.10, 3.11.9, 3.13.3, 3.9.13]
    runs-on: ${{ matrix.os }}
    steps:
      


      - shell: python
        run: |
         import socket
         socket.gethostname()
         
      - shell: python
        run: |
         import socket
         socket.getfqdn()
