name: Check Xcode Setup

on:
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-14-xlarge','macos-15', 'macos-15-large']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
      - name: List of all ios simulators
        run: |
            xcrun simctl list devices
