name: Check Xcode Setup

on:
  workflow_dispatch:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14','macos-14-xlarge','macos-15', 'macos-15-large']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
      - name: List of all ios simulators
        run: |
            xcrun simctl list devices
      - name: Check Xcode Command Line Tools
        run: |
          if xcode-select -p; 
          then echo "Xcode Command Line Tools are already installed."
          else echo "Installing Xcode Command Line Tools..." 
          xcode-select --install
          fi
      - name: Check Xcode installation
        run: |
          if [ -d "/Applications/Xcode_16.2.0.app" ]; then
            echo "Xcode is installed."
          else
            echo "Xcode is not installed."
            exit 1
          fi
  
      - name: List available SDKs
        run: |
          xcodebuild -showsdks
            xcrun -sdk macosx --show-sdk-path
      - name: Verify SDK path
        run: |
          if [ -d "/Applications/Xcode_16.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" ]; then
            echo "SDK path is valid."
          else
            echo "SDK path is invalid."
            exit 1
          fi
      - name: check file permissions
        run: |
           stat /Applications/Xcode_16.2.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
      - name: check whoami
        run: |
         whoami
         id
           # macOS SDK version
           # xcrun --show-sdk-version
        
